-- ApexTech | Enterprise Sales & Profitability 360
-- Databricks (Unity Catalog) DDL. Generated by src/emit_ddl.py.

CREATE CATALOG IF NOT EXISTS apextech;
CREATE SCHEMA  IF NOT EXISTS apextech.sales;
USE apextech.sales;

CREATE OR REPLACE TABLE dim_channel (
    channel_id      SMALLINT,
    sales_channel   VARCHAR(26),
    channel_group   VARCHAR(20),
    is_digital      SMALLINT,
    target_mix_pct  DECIMAL(12,6)
)
USING DELTA;
ALTER TABLE dim_channel ALTER COLUMN channel_id SET NOT NULL;
ALTER TABLE dim_channel ADD CONSTRAINT pk_dim_channel PRIMARY KEY (channel_id);

CREATE OR REPLACE TABLE dim_country (
    country_id          INT,
    country             VARCHAR(29),
    country_code        VARCHAR(16),
    region              VARCHAR(27),
    market              VARCHAR(35),
    currency_code       VARCHAR(16),
    geo_level1_global   VARCHAR(17),
    geo_level2_region   VARCHAR(27),
    geo_level3_country  VARCHAR(29)
)
USING DELTA;

CREATE OR REPLACE TABLE dim_currency (
    currency_code          VARCHAR(16),
    currency_name          VARCHAR(33),
    is_reporting_currency  SMALLINT
)
USING DELTA;
ALTER TABLE dim_currency ALTER COLUMN currency_code SET NOT NULL;
ALTER TABLE dim_currency ADD CONSTRAINT pk_dim_currency PRIMARY KEY (currency_code);

CREATE OR REPLACE TABLE dim_customer (
    customer_id              INT,
    customer_name            VARCHAR(65),
    customer_type            VARCHAR(23),
    customer_segment         VARCHAR(23),
    industry                 VARCHAR(39),
    customer_tier            VARCHAR(21),
    country                  VARCHAR(29),
    region                   VARCHAR(27),
    state                    VARCHAR(41),
    city                     VARCHAR(29),
    currency_code            VARCHAR(16),
    primary_location_id      BIGINT,
    sales_channel            VARCHAR(26),
    account_manager_id       BIGINT,
    customer_since_date      DATE,
    credit_rating            VARCHAR(16),
    payment_terms            VARCHAR(24),
    annual_revenue_band      VARCHAR(24),
    is_active                SMALLINT,
    is_strategic_customer    SMALLINT,
    _spend_weight            DECIMAL(12,6),
    customer_lifetime_value  DECIMAL(18,2),
    cust_level1_segment      VARCHAR(23),
    cust_level2_industry     VARCHAR(39),
    cust_level3_tier         VARCHAR(21),
    cust_level4_customer     VARCHAR(65)
)
USING DELTA;
ALTER TABLE dim_customer ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE dim_customer ADD CONSTRAINT pk_dim_customer PRIMARY KEY (customer_id);

CREATE OR REPLACE TABLE dim_date (
    calendar_date           DATE,
    date_key                INT,
    day_of_month            SMALLINT,
    day_of_week             SMALLINT,
    day_of_year             SMALLINT,
    day_name                VARCHAR(21),
    is_weekend              SMALLINT,
    week_of_year            SMALLINT,
    iso_year                SMALLINT,
    iso_year_week           VARCHAR(20),
    iso_year_week_key       INT,
    week_start_date         DATE,
    week_end_date           DATE,
    month_number            SMALLINT,
    month_name              VARCHAR(21),
    month_short_name        VARCHAR(16),
    quarter_number          SMALLINT,
    quarter_name            VARCHAR(16),
    year_number             SMALLINT,
    year_month              VARCHAR(18),
    year_month_key          INT,
    year_quarter            VARCHAR(18),
    month_start_date        DATE,
    month_end_date          DATE,
    fiscal_year             SMALLINT,
    fiscal_quarter          SMALLINT,
    fiscal_quarter_name     VARCHAR(16),
    fiscal_month            SMALLINT,
    fiscal_week             SMALLINT,
    fiscal_year_month       VARCHAR(21),
    retail_year             BIGINT,
    retail_454_week         BIGINT,
    retail_454_period       BIGINT,
    retail_454_quarter      BIGINT,
    retail_pattern          VARCHAR(16),
    retail_454_period_name  VARCHAR(16),
    is_month_end            SMALLINT,
    is_month_start          SMALLINT,
    is_quarter_end          SMALLINT,
    is_year_end             SMALLINT,
    holiday_name            VARCHAR(47),
    is_holiday              SMALLINT,
    is_business_day         SMALLINT
)
USING DELTA;
ALTER TABLE dim_date ALTER COLUMN date_key SET NOT NULL;
ALTER TABLE dim_date ADD CONSTRAINT pk_dim_date PRIMARY KEY (date_key);

CREATE OR REPLACE TABLE dim_exchange_rate (
    year_month_key  INT,
    year_month      VARCHAR(18),
    currency_code   VARCHAR(16),
    rate_to_usd     DECIMAL(18,8),
    usd_to_local    DECIMAL(18,6)
)
USING DELTA;

CREATE OR REPLACE TABLE dim_location (
    location_id          INT,
    location_name        VARCHAR(54),
    location_type        VARCHAR(36),
    store_type           VARCHAR(20),
    country_id           INT,
    region               VARCHAR(27),
    country              VARCHAR(29),
    country_code         VARCHAR(16),
    state                VARCHAR(41),
    city                 VARCHAR(29),
    market               VARCHAR(35),
    territory            VARCHAR(65),
    currency_code        VARCHAR(16),
    latitude             DECIMAL(9,5),
    longitude            DECIMAL(9,5),
    is_active            SMALLINT,
    geo_level1_global    VARCHAR(17),
    geo_level2_region    VARCHAR(27),
    geo_level3_country   VARCHAR(29),
    geo_level4_state     VARCHAR(41),
    geo_level5_city      VARCHAR(29),
    geo_level6_location  VARCHAR(54)
)
USING DELTA;
ALTER TABLE dim_location ALTER COLUMN location_id SET NOT NULL;
ALTER TABLE dim_location ADD CONSTRAINT pk_dim_location PRIMARY KEY (location_id);

CREATE OR REPLACE TABLE dim_product (
    product_id                  INT,
    sku                         VARCHAR(29),
    product_name                VARCHAR(44),
    sku_description             VARCHAR(72),
    category                    VARCHAR(24),
    subcategory                 VARCHAR(36),
    brand                       VARCHAR(20),
    product_family              VARCHAR(38),
    variant                     VARCHAR(32),
    color                       VARCHAR(20),
    generation                  BIGINT,
    list_price                  DECIMAL(18,2),
    product_launch_date         DATE,
    product_end_date            DATE,
    product_lifecycle_stage     VARCHAR(24),
    demand_weight               DECIMAL(12,6),
    target_margin_pct           DECIMAL(12,6),
    standard_cost               DECIMAL(18,2),
    supplier_id                 INT,
    is_premium                  SMALLINT,
    is_new_product              SMALLINT,
    is_discontinued             SMALLINT,
    is_active                   SMALLINT,
    product_category_id         INT,
    product_level1_category     VARCHAR(24),
    product_level2_subcategory  VARCHAR(36),
    product_level3_brand        VARCHAR(20),
    product_level4_family       VARCHAR(38),
    product_level5_product      VARCHAR(44),
    product_level6_sku          VARCHAR(29)
)
USING DELTA;
ALTER TABLE dim_product ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE dim_product ADD CONSTRAINT pk_dim_product PRIMARY KEY (product_id);

CREATE OR REPLACE TABLE dim_product_category (
    product_category_id         INT,
    category                    VARCHAR(36),
    subcategory                 VARCHAR(36),
    product_level1_category     VARCHAR(36),
    product_level2_subcategory  VARCHAR(36)
)
USING DELTA;

CREATE OR REPLACE TABLE dim_promotion (
    promotion_id        INT,
    promotion_name      VARCHAR(54),
    promotion_type      VARCHAR(35),
    promotion_category  VARCHAR(21),
    start_date          DATE,
    end_date            DATE,
    discount_pct        DECIMAL(12,6),
    promotion_budget    DECIMAL(18,2),
    target_category     VARCHAR(36),
    target_segment      VARCHAR(26),
    campaign_channel    VARCHAR(29)
)
USING DELTA;
ALTER TABLE dim_promotion ALTER COLUMN promotion_id SET NOT NULL;
ALTER TABLE dim_promotion ADD CONSTRAINT pk_dim_promotion PRIMARY KEY (promotion_id);

CREATE OR REPLACE TABLE dim_sales_rep (
    sales_rep_id         INT,
    sales_rep_name       VARCHAR(32),
    sales_region         VARCHAR(27),
    sales_team           VARCHAR(38),
    territory            VARCHAR(32),
    manager_name         VARCHAR(39),
    director_name        VARCHAR(36),
    vp_name              VARCHAR(29),
    hire_date            DATE,
    annual_quota         DECIMAL(18,4),
    employment_status    VARCHAR(23),
    is_active            SMALLINT,
    rep_level1_vp        VARCHAR(29),
    rep_level2_region    VARCHAR(27),
    rep_level3_director  VARCHAR(36),
    rep_level4_manager   VARCHAR(39),
    rep_level5_rep       VARCHAR(32)
)
USING DELTA;
ALTER TABLE dim_sales_rep ALTER COLUMN sales_rep_id SET NOT NULL;
ALTER TABLE dim_sales_rep ADD CONSTRAINT pk_dim_sales_rep PRIMARY KEY (sales_rep_id);

CREATE OR REPLACE TABLE dim_supplier (
    supplier_id             INT,
    supplier_name           VARCHAR(48),
    supplier_group          VARCHAR(39),
    supplier_region         VARCHAR(27),
    country                 VARCHAR(29),
    supplier_tier           VARCHAR(17),
    supplier_category       VARCHAR(41),
    payment_terms           VARCHAR(24),
    contract_start_date     DATE,
    contract_end_date       DATE,
    quality_rating          DECIMAL(5,1),
    risk_rating             VARCHAR(20),
    default_lead_time_days  BIGINT,
    is_strategic_supplier   SMALLINT,
    supplier_level1_region  VARCHAR(27),
    supplier_level2_group   VARCHAR(39),
    supplier_level3_tier    VARCHAR(17),
    supplier_level4_name    VARCHAR(48)
)
USING DELTA;
ALTER TABLE dim_supplier ALTER COLUMN supplier_id SET NOT NULL;
ALTER TABLE dim_supplier ADD CONSTRAINT pk_dim_supplier PRIMARY KEY (supplier_id);

CREATE OR REPLACE TABLE fact_budget (
    year_month_key       INT,
    budget_month         DATE,
    country_id           INT,
    region               VARCHAR(17),
    country              VARCHAR(24),
    product_category_id  INT,
    category             VARCHAR(36),
    subcategory          VARCHAR(36),
    channel_id           SMALLINT,
    sales_channel        VARCHAR(26),
    budget_sales         DECIMAL(18,2),
    budget_quantity      BIGINT,
    budget_cost          DECIMAL(18,2),
    budget_profit        DECIMAL(18,2),
    budget_margin_pct    DECIMAL(12,6)
)
USING DELTA
CLUSTER BY (year_month_key);

CREATE OR REPLACE TABLE fact_forecast (
    year_month_key       INT,
    forecast_month       DATE,
    forecast_version     VARCHAR(30),
    country_id           INT,
    region               VARCHAR(17),
    country              VARCHAR(24),
    product_category_id  INT,
    category             VARCHAR(36),
    subcategory          VARCHAR(36),
    channel_id           SMALLINT,
    sales_channel        VARCHAR(26),
    forecast_sales       DECIMAL(18,2),
    forecast_quantity    BIGINT,
    forecast_cost        DECIMAL(18,2),
    forecast_profit      DECIMAL(18,2),
    forecast_margin_pct  DECIMAL(12,6),
    confidence_low       DECIMAL(18,2),
    confidence_high      DECIMAL(18,2)
)
USING DELTA
CLUSTER BY (year_month_key);

CREATE OR REPLACE TABLE fact_inventory (
    snapshot_date          DATE,
    location_id            INT,
    product_id             INT,
    opening_inventory      DECIMAL(18,4),
    received_quantity      DECIMAL(18,4),
    sold_quantity          DECIMAL(18,4),
    ending_inventory       DECIMAL(18,4),
    reserved_quantity      DECIMAL(18,4),
    available_inventory    DECIMAL(18,4),
    inventory_value        DECIMAL(18,2),
    stockout_flag          SMALLINT,
    lost_sales_units       DECIMAL(18,2),
    days_of_supply         DECIMAL(10,1),
    date_key               INT,
    year_month_key         INT,
    is_below_safety_stock  SMALLINT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);

CREATE OR REPLACE TABLE fact_returns (
    return_id          BIGINT,
    order_line_id      BIGINT,
    return_date        DATE,
    date_key           INT,
    year_month_key     INT,
    order_date         DATE,
    customer_id        INT,
    product_id         INT,
    supplier_id        INT,
    location_id        INT,
    return_quantity    INT,
    return_amount      DECIMAL(18,2),
    return_reason      VARCHAR(41),
    return_category    VARCHAR(24),
    product_condition  VARCHAR(35),
    refund_amount      DECIMAL(18,2),
    days_to_return     BIGINT,
    is_defect_related  SMALLINT
)
USING DELTA
CLUSTER BY (year_month_key);
ALTER TABLE fact_returns ALTER COLUMN return_id SET NOT NULL;
ALTER TABLE fact_returns ADD CONSTRAINT pk_fact_returns PRIMARY KEY (return_id);

CREATE OR REPLACE TABLE fact_sales_order (
    order_id               BIGINT,
    order_date             DATE,
    date_key               INT,
    year_month_key         INT,
    customer_id            INT,
    location_id            INT,
    sales_rep_id           INT,
    channel_id             SMALLINT,
    sales_channel          VARCHAR(26),
    order_status           VARCHAR(21),
    payment_method         VARCHAR(29),
    ship_method            VARCHAR(32),
    order_priority         VARCHAR(20),
    requested_ship_date    DATE,
    actual_ship_date       DATE,
    currency_code          VARCHAR(16),
    exchange_rate          DECIMAL(18,8),
    line_count             SMALLINT,
    total_order_amount     DECIMAL(18,2),
    total_gross_amount     DECIMAL(18,2),
    total_discount_amount  DECIMAL(18,2),
    total_cost_amount      DECIMAL(18,2),
    total_tax_amount       DECIMAL(18,2),
    total_gross_profit     DECIMAL(18,2),
    total_quantity         INT
)
USING DELTA
CLUSTER BY (year_month_key, customer_id);
ALTER TABLE fact_sales_order ALTER COLUMN order_id SET NOT NULL;
ALTER TABLE fact_sales_order ADD CONSTRAINT pk_fact_sales_order PRIMARY KEY (order_id);

CREATE OR REPLACE TABLE fact_sales_order_line (
    order_line_id        BIGINT,
    order_id             BIGINT,
    line_number          SMALLINT,
    order_date           DATE,
    date_key             INT,
    year_month_key       INT,
    customer_id          INT,
    product_id           INT,
    supplier_id          INT,
    location_id          INT,
    sales_rep_id         INT,
    promotion_id         INT,
    channel_id           SMALLINT,
    product_category_id  INT,
    country_id           INT,
    sales_channel        VARCHAR(26),
    order_status         VARCHAR(21),
    quantity             INT,
    list_price           DECIMAL(18,2),
    unit_price           DECIMAL(18,2),
    unit_cost            DECIMAL(18,4),
    discount_pct         DECIMAL(12,6),
    gross_sales          DECIMAL(18,2),
    discount_amount      DECIMAL(18,2),
    net_sales            DECIMAL(18,2),
    cost                 DECIMAL(18,2),
    shipping_cost        DECIMAL(18,2),
    tax_amount           DECIMAL(18,2),
    gross_profit         DECIMAL(18,2),
    currency_code        VARCHAR(16),
    exchange_rate        DECIMAL(18,8),
    lead_time_days       SMALLINT,
    gross_margin_pct     DECIMAL(12,6),
    gross_sales_lc       DECIMAL(18,2),
    net_sales_lc         DECIMAL(18,2),
    gross_profit_lc      DECIMAL(18,2),
    cost_lc              DECIMAL(18,2),
    discount_amount_lc   DECIMAL(18,2)
)
USING DELTA
CLUSTER BY (year_month_key, product_id);
ALTER TABLE fact_sales_order_line ALTER COLUMN order_line_id SET NOT NULL;
ALTER TABLE fact_sales_order_line ADD CONSTRAINT pk_fact_sales_order_line PRIMARY KEY (order_line_id);

CREATE OR REPLACE TABLE fact_sales_rep_quota (
    year_month_key  INT,
    quota_month     DATE,
    sales_rep_id    INT,
    sales_region    VARCHAR(27),
    quota_amount    DECIMAL(18,2),
    actual_sales    DECIMAL(18,2),
    attainment_pct  DECIMAL(12,6)
)
USING DELTA;

CREATE OR REPLACE TABLE fact_supplier_performance (
    year_month_key          INT,
    month_start_date        DATE,
    supplier_id             INT,
    product_id              INT,
    orders                  INT,
    units_ordered           BIGINT,
    units_received          BIGINT,
    units_defective         BIGINT,
    defect_rate             DECIMAL(12,6),
    on_time_deliveries      BIGINT,
    late_deliveries         BIGINT,
    average_lead_time_days  DECIMAL(10,1),
    supplier_cost           DECIMAL(18,2),
    unit_cost               DECIMAL(18,4),
    cost_change_pct         DECIMAL(12,6),
    quality_score           DECIMAL(12,6),
    delivery_score          DECIMAL(12,6),
    supplier_score          DECIMAL(12,6)
)
USING DELTA;
