#!/usr/bin/env python3
"""Emit platform DDL and load scripts from the generated parquet schemas.

Deriving the DDL from the data (rather than hand-writing it) means the types
can never drift from what the generator actually produces.

  python3 src/emit_ddl.py --tier full
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq

sys.path.insert(0, str(Path(__file__).resolve().parent))
from apexconfig import PROJECT_ROOT

# Money, ratios and coordinates need explicit scale. Floats would let the
# profit waterfall drift away from the KPI tile it is supposed to reconcile to.
MONEY_SUFFIXES = ("_amount", "_sales", "_cost", "_profit", "_value", "_price",
                  "_budget", "_lc", "_low", "_high", "_ltv")
RATIO_SUFFIXES = ("_pct", "_rate", "_score", "_weight", "_ratio")
# Money columns whose name does not end in a money suffix.
MONEY_EXACT = {"cost", "shipping_cost", "supplier_cost", "quota_amount"}

DECIMAL_OVERRIDES = {
    "exchange_rate": (18, 8), "rate_to_usd": (18, 8), "usd_to_local": (18, 6),
    "latitude": (9, 5), "longitude": (9, 5),
    "customer_lifetime_value": (18, 2), "quality_rating": (5, 1),
    "days_of_supply": (10, 1), "average_lead_time_days": (10, 1),
    "unit_cost": (18, 4), "lost_sales_units": (18, 2),
}

PRIMARY_KEYS = {
    "dim_date": "date_key", "dim_customer": "customer_id",
    "dim_product": "product_id", "dim_supplier": "supplier_id",
    "dim_location": "location_id", "dim_promotion": "promotion_id",
    "dim_sales_rep": "sales_rep_id", "dim_channel": "channel_id",
    "dim_currency": "currency_code",
    "fact_sales_order": "order_id", "fact_sales_order_line": "order_line_id",
    "fact_returns": "return_id",
}

CLUSTER_KEYS = {
    "fact_sales_order_line": ["year_month_key", "product_id"],
    "fact_sales_order": ["year_month_key", "customer_id"],
    "fact_returns": ["year_month_key"],
    "fact_inventory": ["year_month_key", "product_id"],
    "fact_budget": ["year_month_key"], "fact_forecast": ["year_month_key"],
}


def sql_type(col: str, dtype, dialect: str) -> str:
    name = str(dtype)
    if name.startswith(("int", "uint")):
        width = int("".join(c for c in name if c.isdigit()) or 64)
        if width <= 16:
            return "SMALLINT"
        return "INT" if width <= 32 else "BIGINT"
    if name.startswith("bool"):
        return "BOOLEAN"
    if name.startswith(("datetime", "timestamp")):
        return "TIMESTAMP_NTZ" if dialect == "snowflake" else "TIMESTAMP"
    if name.startswith("float") or name == "double":
        if col in MONEY_EXACT:
            return f"{'NUMBER' if dialect == 'snowflake' else 'DECIMAL'}(18,2)"
        if col in DECIMAL_OVERRIDES:
            p, sc = DECIMAL_OVERRIDES[col]
        elif col.endswith(MONEY_SUFFIXES):
            p, sc = 18, 2
        elif col.endswith(RATIO_SUFFIXES) or "margin" in col:
            p, sc = 12, 6
        else:
            p, sc = 18, 4
        return f"{'NUMBER' if dialect == 'snowflake' else 'DECIMAL'}({p},{sc})"
    # object columns: dates come back as python date objects, not strings
    return "OBJECT"


def resolve_object(series: pd.Series, dialect: str) -> str:
    non_null = series.dropna()
    if len(non_null) and hasattr(non_null.iloc[0], "isoformat"):
        return "DATE"
    width = int(non_null.astype(str).str.len().max()) if len(non_null) else 16
    width = max(16, min(int(width * 1.5) + 8, 1000))
    return f"VARCHAR({width})"


def build_schema(data_dir: Path, dialect: str) -> dict[str, list[tuple[str, str]]]:
    out = {}
    for path in sorted(data_dir.glob("*.parquet")):
        # Read a sample for object-column resolution; schema comes from metadata.
        head = pd.read_parquet(path).head(2000)
        cols = []
        for col in head.columns:
            t = sql_type(col, head[col].dtype, dialect)
            if t == "OBJECT":
                t = resolve_object(head[col], dialect)
            cols.append((col, t))
        out[path.stem] = cols
    return out


def emit_snowflake(schema: dict, out_dir: Path, tier: str) -> None:
    L = ["-- ApexTech | Enterprise Sales & Profitability 360",
         "-- Snowflake DDL. Generated by src/emit_ddl.py - do not hand-edit.",
         "",
         "CREATE DATABASE IF NOT EXISTS APEXTECH;",
         "CREATE SCHEMA   IF NOT EXISTS APEXTECH.SALES;",
         "USE SCHEMA APEXTECH.SALES;",
         ""]
    for table, cols in schema.items():
        width = max(len(c) for c, _ in cols) + 2
        body = ",\n".join(f"    {c:<{width}}{t}" for c, t in cols)
        L.append(f"CREATE OR REPLACE TABLE {table} (\n{body}\n)")
        if table in CLUSTER_KEYS:
            L[-1] += f"\nCLUSTER BY ({', '.join(CLUSTER_KEYS[table])})"
        L[-1] += ";"
        if table in PRIMARY_KEYS:
            L.append(f"ALTER TABLE {table} ADD PRIMARY KEY ({PRIMARY_KEYS[table]});")
        L.append("")
    (out_dir / "01_ddl.sql").write_text("\n".join(L))

    ld = ["-- Load parquet into Snowflake.",
          "-- 1. Put the files somewhere Snowflake can read them.",
          "-- 2. Run this script.",
          "",
          "USE SCHEMA APEXTECH.SALES;",
          "",
          "CREATE OR REPLACE FILE FORMAT apex_parquet TYPE = PARQUET;",
          "CREATE OR REPLACE STAGE apex_stage FILE_FORMAT = apex_parquet;",
          "",
          f"-- From a local machine (SnowSQL only), for the '{tier}' tier:",
          f"--   PUT file://<abs-path>/data/{tier}/*.parquet @apex_stage "
          "AUTO_COMPRESS=FALSE;",
          "-- Or point the stage at your own S3/Azure/GCS location instead.",
          ""]
    for table in schema:
        ld += [f"COPY INTO {table}",
               f"  FROM @apex_stage/{table}.parquet",
               "  FILE_FORMAT = (FORMAT_NAME = apex_parquet)",
               "  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE",
               "  ON_ERROR = ABORT_STATEMENT;", ""]
    ld += ["-- Sanity check: these three numbers drive the executive KPI row.",
           "SELECT COUNT(*) AS order_lines,",
           "       ROUND(SUM(net_sales)   / 1e6, 1) AS net_sales_musd,",
           "       ROUND(SUM(gross_profit) / 1e6, 1) AS gross_profit_musd",
           "FROM   fact_sales_order_line;"]
    (out_dir / "02_load.sql").write_text("\n".join(ld))


def emit_databricks(schema: dict, out_dir: Path, tier: str) -> None:
    L = ["-- ApexTech | Enterprise Sales & Profitability 360",
         "-- Databricks (Unity Catalog) DDL. Generated by src/emit_ddl.py.",
         "",
         "CREATE CATALOG IF NOT EXISTS apextech;",
         "CREATE SCHEMA  IF NOT EXISTS apextech.sales;",
         "USE apextech.sales;",
         ""]
    for table, cols in schema.items():
        width = max(len(c) for c, _ in cols) + 2
        body = ",\n".join(f"    {c:<{width}}{t}" for c, t in cols)
        L.append(f"CREATE OR REPLACE TABLE {table} (\n{body}\n)")
        L[-1] += "\nUSING DELTA"
        if table in CLUSTER_KEYS:
            L[-1] += f"\nCLUSTER BY ({', '.join(CLUSTER_KEYS[table])})"
        L[-1] += ";"
        if table in PRIMARY_KEYS:
            pk = PRIMARY_KEYS[table]
            L.append(f"ALTER TABLE {table} ALTER COLUMN {pk} SET NOT NULL;")
            L.append(f"ALTER TABLE {table} ADD CONSTRAINT pk_{table} "
                     f"PRIMARY KEY ({pk});")
        L.append("")
    (out_dir / "01_ddl.sql").write_text("\n".join(L))

    py = f'''"""Load the ApexTech parquet files into Unity Catalog.

Run as a Databricks notebook or with databricks-connect. Upload the parquet
directory to a volume first, e.g.:

    databricks fs cp -r data/{tier} dbfs:/Volumes/apextech/sales/raw/
"""

CATALOG = "apextech"
SCHEMA = "sales"
SOURCE = "/Volumes/apextech/sales/raw"        # adjust to your volume

TABLES = {list(schema)!r}

spark.sql(f"CREATE CATALOG IF NOT EXISTS {{CATALOG}}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{CATALOG}}.{{SCHEMA}}")

for table in TABLES:
    df = spark.read.parquet(f"{{SOURCE}}/{{table}}.parquet")
    (df.write
       .mode("overwrite")
       .option("overwriteSchema", "true")
       .saveAsTable(f"{{CATALOG}}.{{SCHEMA}}.{{table}}"))
    print(f"loaded {{table}}: {{df.count():,}} rows")

# Liquid clustering on the tables that carry the analytical load.
for table, keys in {CLUSTER_KEYS!r}.items():
    spark.sql(f"ALTER TABLE {{CATALOG}}.{{SCHEMA}}.{{table}} "
              f"CLUSTER BY ({{', '.join(keys)}})")

spark.sql(f"""
    SELECT COUNT(*)                        AS order_lines,
           ROUND(SUM(net_sales)   / 1e6, 1) AS net_sales_musd,
           ROUND(SUM(gross_profit) / 1e6, 1) AS gross_profit_musd
    FROM   {{CATALOG}}.{{SCHEMA}}.fact_sales_order_line
""").show()
'''
    (out_dir / "02_load.py").write_text(py)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tier", default="full", choices=["small", "full"])
    ap.add_argument("--data", default=None)
    args = ap.parse_args(argv)

    data_dir = Path(args.data) if args.data else PROJECT_ROOT / "data" / args.tier
    if not data_dir.exists():
        print(f"no data at {data_dir}; run generate.py first")
        return 2

    for dialect, emit in (("snowflake", emit_snowflake), ("databricks", emit_databricks)):
        out_dir = PROJECT_ROOT / "sql" / dialect
        out_dir.mkdir(parents=True, exist_ok=True)
        emit(build_schema(data_dir, dialect), out_dir, args.tier)
        print(f"  wrote sql/{dialect}/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
