# Load parquet into Databricks. Point BASE at the uploaded folder.
BASE = "dbfs:/FileStore/p2p/full"
SCHEMA = "p2p"

spark.sql(f"CREATE DATABASE IF NOT EXISTS {SCHEMA}")

spark.read.parquet(f"{BASE}/contract.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.contract")
spark.read.parquet(f"{BASE}/contract_price.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.contract_price")
spark.read.parquet(f"{BASE}/dim_approval_policy.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_approval_policy")
spark.read.parquet(f"{BASE}/dim_category.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_category")
spark.read.parquet(f"{BASE}/dim_company_code.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_company_code")
spark.read.parquet(f"{BASE}/dim_cost_center.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_cost_center")
spark.read.parquet(f"{BASE}/dim_currency.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_currency")
spark.read.parquet(f"{BASE}/dim_date.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_date")
spark.read.parquet(f"{BASE}/dim_department.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_department")
spark.read.parquet(f"{BASE}/dim_employee.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_employee")
spark.read.parquet(f"{BASE}/dim_exchange_rate.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_exchange_rate")
spark.read.parquet(f"{BASE}/dim_gl_account.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_gl_account")
spark.read.parquet(f"{BASE}/dim_hold_reason.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_hold_reason")
spark.read.parquet(f"{BASE}/dim_item.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_item")
spark.read.parquet(f"{BASE}/dim_match_tolerance.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_match_tolerance")
spark.read.parquet(f"{BASE}/dim_payment_terms.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_payment_terms")
spark.read.parquet(f"{BASE}/dim_supplier.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_supplier")
spark.read.parquet(f"{BASE}/dim_supplier_bank_account.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_supplier_bank_account")
spark.read.parquet(f"{BASE}/dim_supplier_parent.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_supplier_parent")
spark.read.parquet(f"{BASE}/dim_supplier_site.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_supplier_site")
spark.read.parquet(f"{BASE}/dim_supplier_status_history.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_supplier_status_history")
spark.read.parquet(f"{BASE}/fact_ap_aging_snapshot.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_ap_aging_snapshot")
spark.read.parquet(f"{BASE}/fact_approval_event.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_approval_event")
spark.read.parquet(f"{BASE}/fact_budget.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_budget")
spark.read.parquet(f"{BASE}/fact_goods_receipt.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_goods_receipt")
spark.read.parquet(f"{BASE}/fact_goods_receipt_line.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_goods_receipt_line")
spark.read.parquet(f"{BASE}/fact_invoice.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_invoice")
spark.read.parquet(f"{BASE}/fact_invoice_distribution.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_invoice_distribution")
spark.read.parquet(f"{BASE}/fact_invoice_hold.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_invoice_hold")
spark.read.parquet(f"{BASE}/fact_invoice_line.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_invoice_line")
spark.read.parquet(f"{BASE}/fact_match_result.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_match_result")
spark.read.parquet(f"{BASE}/fact_open_commitment_snapshot.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_open_commitment_snapshot")
spark.read.parquet(f"{BASE}/fact_p2p_cycle.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_p2p_cycle")
spark.read.parquet(f"{BASE}/fact_p2p_exception.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_p2p_exception")
spark.read.parquet(f"{BASE}/fact_payment.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_payment")
spark.read.parquet(f"{BASE}/fact_payment_application.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_payment_application")
spark.read.parquet(f"{BASE}/fact_pcard_transaction.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_pcard_transaction")
spark.read.parquet(f"{BASE}/fact_po_change.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_po_change")
spark.read.parquet(f"{BASE}/fact_purchase_order.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_purchase_order")
spark.read.parquet(f"{BASE}/fact_purchase_order_line.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_purchase_order_line")
spark.read.parquet(f"{BASE}/fact_requisition.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_requisition")
spark.read.parquet(f"{BASE}/fact_requisition_line.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_requisition_line")
spark.read.parquet(f"{BASE}/fact_spend.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_spend")
spark.read.parquet(f"{BASE}/fact_supplier_risk_snapshot.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_supplier_risk_snapshot")