-- Meridian Global Industries | Supply Chain Control Tower
-- Databricks (Unity Catalog) DDL. Generated by src/emit_ddl.py.

CREATE CATALOG IF NOT EXISTS meridian;
CREATE SCHEMA  IF NOT EXISTS meridian.supply_chain;
USE meridian.supply_chain;

CREATE OR REPLACE TABLE dim_carrier (
    carrier_id               INT,
    carrier_code             VARCHAR(16),
    carrier_name             VARCHAR(36),
    transport_mode           VARCHAR(17),
    base_cost_per_km         DECIMAL(12,4),
    contracted_transit_days  INT,
    on_time_rate             DECIMAL(10,4),
    avg_transit_days         DECIMAL(10,2),
    shipment_count           INT,
    total_freight_cost       DECIMAL(18,2)
)
USING DELTA;
ALTER TABLE dim_carrier ALTER COLUMN carrier_id SET NOT NULL;
ALTER TABLE dim_carrier ADD CONSTRAINT pk_dim_carrier PRIMARY KEY (carrier_id);

CREATE OR REPLACE TABLE dim_customer (
    customer_id                   INT,
    customer_name                 VARCHAR(48),
    customer_segment              VARCHAR(24),
    country                       VARCHAR(38),
    region                        VARCHAR(27),
    primary_location_id           INT,
    service_level_agreement_days  INT,
    cust_level1_segment           VARCHAR(24),
    cust_level2_region            VARCHAR(27),
    cust_level3_customer          VARCHAR(48)
)
USING DELTA;
ALTER TABLE dim_customer ALTER COLUMN customer_id SET NOT NULL;
ALTER TABLE dim_customer ADD CONSTRAINT pk_dim_customer PRIMARY KEY (customer_id);

CREATE OR REPLACE TABLE dim_date (
    calendar_date           DATE,
    date_key                INT,
    day_of_month            SMALLINT,
    day_of_week             SMALLINT,
    day_of_year             SMALLINT,
    day_name                VARCHAR(21),
    is_weekend              SMALLINT,
    week_of_year            SMALLINT,
    iso_year                SMALLINT,
    iso_year_week           VARCHAR(20),
    iso_year_week_key       INT,
    week_start_date         DATE,
    week_end_date           DATE,
    month_number            SMALLINT,
    month_name              VARCHAR(21),
    month_short_name        VARCHAR(16),
    quarter_number          SMALLINT,
    quarter_name            VARCHAR(16),
    year_number             SMALLINT,
    year_month              VARCHAR(18),
    year_month_key          INT,
    year_quarter            VARCHAR(18),
    month_start_date        DATE,
    month_end_date          DATE,
    fiscal_year             SMALLINT,
    fiscal_quarter          SMALLINT,
    fiscal_quarter_name     VARCHAR(16),
    fiscal_month            SMALLINT,
    fiscal_week             SMALLINT,
    fiscal_year_month       VARCHAR(21),
    retail_year             BIGINT,
    retail_454_week         BIGINT,
    retail_454_period       BIGINT,
    retail_454_quarter      BIGINT,
    retail_pattern          VARCHAR(16),
    retail_454_period_name  VARCHAR(16),
    is_month_end            SMALLINT,
    is_month_start          SMALLINT,
    is_quarter_end          SMALLINT,
    is_year_end             SMALLINT,
    holiday_name            VARCHAR(47),
    is_holiday              SMALLINT,
    is_business_day         SMALLINT
)
USING DELTA;
ALTER TABLE dim_date ALTER COLUMN date_key SET NOT NULL;
ALTER TABLE dim_date ADD CONSTRAINT pk_dim_date PRIMARY KEY (date_key);

CREATE OR REPLACE TABLE dim_employee (
    employee_id    INT,
    employee_name  VARCHAR(35),
    role           VARCHAR(39),
    region         VARCHAR(27),
    location_id    INT,
    hire_date      DATE
)
USING DELTA;
ALTER TABLE dim_employee ALTER COLUMN employee_id SET NOT NULL;
ALTER TABLE dim_employee ADD CONSTRAINT pk_dim_employee PRIMARY KEY (employee_id);

CREATE OR REPLACE TABLE dim_location (
    location_id            INT,
    location_code          VARCHAR(18),
    location_name          VARCHAR(35),
    city                   VARCHAR(29),
    country                VARCHAR(38),
    sub_region             VARCHAR(21),
    region                 VARCHAR(27),
    node_type              VARCHAR(20),
    capacity_units         INT,
    is_plant               BIGINT,
    opened_offset_months   BIGINT,
    geo_level1_global      VARCHAR(17),
    geo_level2_region      VARCHAR(27),
    geo_level3_country     VARCHAR(38),
    geo_level4_sub_region  VARCHAR(21),
    geo_level5_location    VARCHAR(35)
)
USING DELTA;
ALTER TABLE dim_location ALTER COLUMN location_id SET NOT NULL;
ALTER TABLE dim_location ADD CONSTRAINT pk_dim_location PRIMARY KEY (location_id);

CREATE OR REPLACE TABLE dim_product (
    product_id                  INT,
    product_sku                 VARCHAR(23),
    product_name                VARCHAR(66),
    category                    VARCHAR(39),
    subcategory                 VARCHAR(32),
    product_category_id         INT,
    brand                       VARCHAR(20),
    product_family              VARCHAR(23),
    product_type                VARCHAR(27),
    material                    VARCHAR(30),
    unit_cost                   DECIMAL(18,2),
    standard_price              DECIMAL(18,2),
    weight_kg                   DECIMAL(12,3),
    volume_m3                   DECIMAL(12,4),
    shelf_life_days             INT,
    criticality                 VARCHAR(21),
    primary_supplier_id         INT,
    secondary_supplier_id       INT,
    single_source_flag          SMALLINT,
    country_of_origin           VARCHAR(38),
    abc_class                   VARCHAR(16),
    xyz_class                   VARCHAR(16),
    lead_time_days              INT,
    safety_stock_days           INT,
    product_level1_category     VARCHAR(39),
    product_level2_subcategory  VARCHAR(32),
    product_level3_brand        VARCHAR(20),
    product_level4_family       VARCHAR(23),
    product_level5_product      VARCHAR(66),
    product_level6_sku          VARCHAR(23),
    annual_demand_qty           DECIMAL(18,3),
    demand_cv                   DECIMAL(10,4),
    annual_demand_value         DECIMAL(18,2),
    replenishment_source        VARCHAR(23),
    reorder_point_qty           DECIMAL(18,3),
    target_stock_qty            DECIMAL(18,3)
)
USING DELTA;
ALTER TABLE dim_product ALTER COLUMN product_id SET NOT NULL;
ALTER TABLE dim_product ADD CONSTRAINT pk_dim_product PRIMARY KEY (product_id);

CREATE OR REPLACE TABLE dim_product_category (
    product_category_id  INT,
    category             VARCHAR(39),
    subcategory          VARCHAR(32),
    is_manufactured      BIGINT
)
USING DELTA;
ALTER TABLE dim_product_category ALTER COLUMN product_category_id SET NOT NULL;
ALTER TABLE dim_product_category ADD CONSTRAINT pk_dim_product_category PRIMARY KEY (product_category_id);

CREATE OR REPLACE TABLE dim_region (
    region_id  INT,
    region     VARCHAR(27)
)
USING DELTA;
ALTER TABLE dim_region ALTER COLUMN region_id SET NOT NULL;
ALTER TABLE dim_region ADD CONSTRAINT pk_dim_region PRIMARY KEY (region_id);

CREATE OR REPLACE TABLE dim_supplier (
    supplier_id               BIGINT,
    supplier_master_id        VARCHAR(18),
    supplier_name             VARCHAR(51),
    supplier_name_clean       VARCHAR(51),
    supplier_tier             VARCHAR(21),
    country                   VARCHAR(38),
    region                    VARCHAR(27),
    category                  VARCHAR(39),
    payment_terms             VARCHAR(24),
    lead_time_days            BIGINT,
    minimum_order_qty         BIGINT,
    capacity_units_per_week   BIGINT,
    financial_risk            BIGINT,
    geopolitical_risk         BIGINT,
    quality_score             DECIMAL(7,2),
    on_time_rate              DECIMAL(10,4),
    defect_rate               DECIMAL(10,5),
    risk_score                DECIMAL(12,6),
    risk_level                VARCHAR(20),
    supplier_level1_region    VARCHAR(27),
    supplier_level2_category  VARCHAR(39),
    supplier_level3_tier      VARCHAR(21),
    supplier_level4_name      VARCHAR(51),
    trailing_90d_spend        DECIMAL(18,2),
    skus_supplied             INT,
    critical_skus_supplied    INT,
    single_sourced_skus       INT
)
USING DELTA;
ALTER TABLE dim_supplier ALTER COLUMN supplier_id SET NOT NULL;
ALTER TABLE dim_supplier ADD CONSTRAINT pk_dim_supplier PRIMARY KEY (supplier_id);

CREATE OR REPLACE TABLE fact_demand_signal (
    week_start_date  DATE,
    product_id       INT,
    region_id        INT,
    demand_qty       DECIMAL(18,3),
    year_month_key   INT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);

CREATE OR REPLACE TABLE fact_financial_impact (
    year_month_key  INT,
    cost_category   VARCHAR(42),
    impact_amount   DECIMAL(18,2)
)
USING DELTA;

CREATE OR REPLACE TABLE fact_forecast (
    forecast_month           TIMESTAMP,
    forecast_generated_date  DATE,
    product_id               INT,
    region_id                INT,
    forecast_version         VARCHAR(20),
    forecast_horizon_months  INT,
    forecast_qty             DECIMAL(18,3),
    actual_qty               DECIMAL(18,3),
    confidence_low           DECIMAL(18,4),
    confidence_high          DECIMAL(18,4),
    forecast_error           DECIMAL(18,3),
    abs_pct_error            DECIMAL(12,5),
    forecast_accuracy        DECIMAL(12,5),
    forecast_bias_pct        DECIMAL(12,5),
    year_month_key           INT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);

CREATE OR REPLACE TABLE fact_inventory_snapshot (
    snapshot_date          DATE,
    snapshot_grain         VARCHAR(16),
    product_id             INT,
    location_id            INT,
    on_hand_qty            DECIMAL(18,3),
    reserved_qty           DECIMAL(18,3),
    available_qty          DECIMAL(18,3),
    in_transit_qty         DECIMAL(18,3),
    backorder_qty          DECIMAL(18,3),
    safety_stock_qty       DECIMAL(18,3),
    reorder_point_qty      DECIMAL(18,3),
    demand_qty             DECIMAL(18,3),
    shipped_qty            DECIMAL(18,3),
    served_current_qty     DECIMAL(18,3),
    unmet_qty              DECIMAL(18,3),
    lost_sales_qty         DECIMAL(18,3),
    receipt_qty            DECIMAL(18,3),
    avg_daily_demand       DECIMAL(18,4),
    inventory_value        DECIMAL(18,2),
    days_of_supply         DECIMAL(12,2),
    stockout_flag          SMALLINT,
    excess_inventory_flag  SMALLINT,
    below_reorder_flag     SMALLINT,
    year_month_key         INT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);

CREATE OR REPLACE TABLE fact_production (
    production_id            BIGINT,
    product_id               INT,
    location_id              INT,
    destination_location_id  INT,
    start_date               DATE,
    completion_date          DATE,
    planned_qty              DECIMAL(18,3),
    completed_qty            DECIMAL(18,3),
    scrap_qty                DECIMAL(18,3),
    yield_pct                DECIMAL(8,4),
    production_cost          DECIMAL(18,2),
    year_month_key           INT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);
ALTER TABLE fact_production ALTER COLUMN production_id SET NOT NULL;
ALTER TABLE fact_production ADD CONSTRAINT pk_fact_production PRIMARY KEY (production_id);

CREATE OR REPLACE TABLE fact_purchase_order (
    po_line_id              BIGINT,
    po_id                   BIGINT,
    po_date                 DATE,
    supplier_id             INT,
    supplier_name_raw       VARCHAR(56),
    product_id              INT,
    location_id             INT,
    ordered_qty             DECIMAL(18,3),
    unit_cost               DECIMAL(18,2),
    po_line_value           DECIMAL(18,2),
    requested_date          DATE,
    promised_date           DATE,
    actual_receipt_date     DATE,
    received_qty            DECIMAL(18,3),
    cancelled_qty           DECIMAL(18,3),
    status                  VARCHAR(35),
    planned_lead_time_days  INT,
    actual_lead_time_days   DECIMAL(10,1),
    is_late                 SMALLINT,
    is_expedited            SMALLINT,
    year_month_key          INT,
    fulfilment_month_key    INT
)
USING DELTA
CLUSTER BY (year_month_key, supplier_id);
ALTER TABLE fact_purchase_order ALTER COLUMN po_line_id SET NOT NULL;
ALTER TABLE fact_purchase_order ADD CONSTRAINT pk_fact_purchase_order PRIMARY KEY (po_line_id);

CREATE OR REPLACE TABLE fact_sales_order_line (
    order_line_id     BIGINT,
    order_id          BIGINT,
    order_date        DATE,
    customer_id       INT,
    product_id        INT,
    location_id       INT,
    ordered_qty       DECIMAL(18,3),
    shipped_qty       DECIMAL(18,3),
    unit_price        DECIMAL(18,2),
    discount_pct      DECIMAL(8,4),
    net_revenue       DECIMAL(18,2),
    cost_of_goods     DECIMAL(18,4),
    is_short_shipped  SMALLINT,
    is_line_filled    SMALLINT,
    gross_profit      DECIMAL(18,2),
    year_month_key    INT
)
USING DELTA
CLUSTER BY (year_month_key, product_id);
ALTER TABLE fact_sales_order_line ALTER COLUMN order_line_id SET NOT NULL;
ALTER TABLE fact_sales_order_line ADD CONSTRAINT pk_fact_sales_order_line PRIMARY KEY (order_line_id);

CREATE OR REPLACE TABLE fact_shipment (
    shipment_id             BIGINT,
    order_id                BIGINT,
    customer_id             INT,
    location_id             INT,
    carrier_id              INT,
    ship_date               DATE,
    expected_delivery_date  DATE,
    actual_delivery_date    DATE,
    quantity                DECIMAL(18,4),
    line_count              INT,
    distance_km             DECIMAL(12,1),
    freight_cost            DECIMAL(18,2),
    is_expedited            SMALLINT,
    transit_days            BIGINT,
    delay_days              INT,
    is_on_time              SMALLINT,
    is_in_full              SMALLINT,
    is_otif                 SMALLINT,
    damage_flag             SMALLINT,
    shipping_method         VARCHAR(21),
    year_month_key          INT
)
USING DELTA
CLUSTER BY (year_month_key, carrier_id);
ALTER TABLE fact_shipment ALTER COLUMN shipment_id SET NOT NULL;
ALTER TABLE fact_shipment ADD CONSTRAINT pk_fact_shipment PRIMARY KEY (shipment_id);

CREATE OR REPLACE TABLE fact_supplier_delivery (
    delivery_id           BIGINT,
    po_line_id            BIGINT,
    supplier_id           INT,
    supplier_name_raw     VARCHAR(56),
    product_id            INT,
    location_id           INT,
    promised_date         DATE,
    actual_receipt_date   DATE,
    received_qty          DECIMAL(18,3),
    accepted_qty          DECIMAL(18,3),
    rejected_qty          DECIMAL(18,3),
    defect_rate           DECIMAL(10,5),
    delay_days            BIGINT,
    is_on_time            SMALLINT,
    unit_cost             DECIMAL(18,2),
    fulfilment_month_key  INT,
    receipt_value         DECIMAL(18,2),
    quality_cost          DECIMAL(18,2),
    year_month_key        INT
)
USING DELTA
CLUSTER BY (year_month_key, supplier_id);
ALTER TABLE fact_supplier_delivery ALTER COLUMN delivery_id SET NOT NULL;
ALTER TABLE fact_supplier_delivery ADD CONSTRAINT pk_fact_supplier_delivery PRIMARY KEY (delivery_id);

CREATE OR REPLACE TABLE fact_supply_chain_risk (
    year_month_key      INT,
    entity_type         VARCHAR(20),
    entity_id           INT,
    supplier_risk       DECIMAL(12,6),
    quality_risk        DECIMAL(12,6),
    logistics_risk      DECIMAL(12,6),
    demand_risk         DECIMAL(12,6),
    inventory_risk      DECIMAL(12,6),
    overall_risk_score  DECIMAL(12,6),
    risk_level          VARCHAR(17)
)
USING DELTA
CLUSTER BY (year_month_key);
