# Load parquet into Databricks. Point BASE at the uploaded folder.
BASE = "dbfs:/FileStore/p2p/full"
SCHEMA = "p2p"

spark.sql(f"CREATE DATABASE IF NOT EXISTS {SCHEMA}")

spark.read.parquet(f"{BASE}/dim_activity_type.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_activity_type")
spark.read.parquet(f"{BASE}/dim_ad_creative.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_ad_creative")
spark.read.parquet(f"{BASE}/dim_attribution_model.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_attribution_model")
spark.read.parquet(f"{BASE}/dim_campaign.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_campaign")
spark.read.parquet(f"{BASE}/dim_channel.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_channel")
spark.read.parquet(f"{BASE}/dim_contact.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_contact")
spark.read.parquet(f"{BASE}/dim_content_asset.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_content_asset")
spark.read.parquet(f"{BASE}/dim_customer.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_customer")
spark.read.parquet(f"{BASE}/dim_date.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_date")
spark.read.parquet(f"{BASE}/dim_geography.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_geography")
spark.read.parquet(f"{BASE}/dim_industry.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_industry")
spark.read.parquet(f"{BASE}/dim_lead_source.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_lead_source")
spark.read.parquet(f"{BASE}/dim_lost_reason.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_lost_reason")
spark.read.parquet(f"{BASE}/dim_opportunity_stage.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_opportunity_stage")
spark.read.parquet(f"{BASE}/dim_product.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_product")
spark.read.parquet(f"{BASE}/dim_sales_rep.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_sales_rep")
spark.read.parquet(f"{BASE}/dim_segment.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.dim_segment")
spark.read.parquet(f"{BASE}/fact_ad_performance.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_ad_performance")
spark.read.parquet(f"{BASE}/fact_attribution_touch.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_attribution_touch")
spark.read.parquet(f"{BASE}/fact_budget_scenario.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_budget_scenario")
spark.read.parquet(f"{BASE}/fact_campaign_daily.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_campaign_daily")
spark.read.parquet(f"{BASE}/fact_campaign_summary.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_campaign_summary")
spark.read.parquet(f"{BASE}/fact_channel_response_curve.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_channel_response_curve")
spark.read.parquet(f"{BASE}/fact_email_event.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_email_event")
spark.read.parquet(f"{BASE}/fact_email_send.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_email_send")
spark.read.parquet(f"{BASE}/fact_funnel_snapshot.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_funnel_snapshot")
spark.read.parquet(f"{BASE}/fact_lead.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_lead")
spark.read.parquet(f"{BASE}/fact_lead_activity.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_lead_activity")
spark.read.parquet(f"{BASE}/fact_marketing_budget.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_marketing_budget")
spark.read.parquet(f"{BASE}/fact_opportunity.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_opportunity")
spark.read.parquet(f"{BASE}/fact_opportunity_stage.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_opportunity_stage")
spark.read.parquet(f"{BASE}/fact_web_event.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_web_event")
spark.read.parquet(f"{BASE}/fact_web_session.parquet").write.mode("overwrite").saveAsTable(f"{SCHEMA}.fact_web_session")